name: BanWarn
api: [1.13.0, 2.0.0]
version: 1.2.0-InDev-alpha3
load: POSTWORLD
main: robske_110\BanWarn\Main
author: robske_110
website: https://github.com/robske110/BanWarn

commands:
 warn:
  description: Warnt einen Spieler
  usage: "/warn <SpielerName> <Grund> [Punkte]"
  permission: ServerCore.command.warn
 warninfo:
  description: Gibt Infos über die Warnungspunkte eines Spielers und die Gründe
  usage: "/warninfo <SpielerName>"
  permission: ServerCore.command.warninfo
  aliases: [wi]

permissions:
 ServerCore.command.warn:
  description: "Erlaubt die benutzung des /warn Kommandos"
  default: op
ServerCore.command.warninfo:
  description: "Erlaubt die benutzung des /warninfo Kommandos"
  default: true
